---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pde2e-builder
  labels:
    app.kubernetes.io/version: "0.1"
    redhat.com/product: podman-desktop
    dev.lifecycle.io/phase: testing
  annotations:
    tekton.dev/pipelines.minVersion: "0.24.x"
    tekton.dev/categories: podman-desktop
    tekton.dev/tags: podman-desktop, testing
    tekton.dev/displayName: "Podman Desktop Building task"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task will prepare the dependencies and build the podman desktop locally

  workspaces:
  - name: pipelines-data
  
  params:
  # Target host parameters
  - name: host
    description: host to connect to the provisioned machine
  - name: username
    description: username to connect to the provisioned machine
  - name: userpassword
    description: user password required to run installers with privileges
  - name: key
    description: key file name to connect to the provisioned machine within the workspace resources path   
  - name: os
    description: type of platform per target host (windows, darwin)
    default: windows
  - name: arch
    description: type of arch per target host for windows only amd64, for darwin amd64 or arm64 
    default: amd64
  - name: workspace-resources-path
    description: path on workspace to find resources to connect to the target machine
  # PDE2E Builder parameters
  - name: image-version
    description: pde2e-builder image version
    default: '0.0.1'
  - name: fork
    description: Podman Desktop repo fork
    default: 'containers'
  - name: branch
    description: Podman Desktop repository branch or tag to checkout
    default: 'main'
  # Results parameters
  - name: workspace-qe-subpath
    description: subpath relative to workspace path where results are stored
    default: qe-results
  - name: results-folder
    description: filename for the junit file holding the e2e results
    default: results
  # Control params
  - name: target-cleanup
    description: 'this param controls if folder on target host will be removed. Defaults true'
    default: 'true'
  - name: debug
    description: debug purposes extend verbosity on cmds executed on the target
    default: 'false'

  results:
  - name: duration
    description: total amount of time in seconds for the qe execution
  - name: pd-path
    description: a path to the built podman desktop app

  steps:
  - name: e2e
    image: quay.io/odockal/pde2e-builder:v$(params.image-version)-$(params.os)
    # We do not have a strict control on versions (as so they can be override)
    # force here to pull everytime just in case it is overriden
    imagePullPolicy: Always
    script: |
      #!/bin/bash

      # This is kept the same as in other tasks
      # Prepare ENVs
      SECONDS=0
      TARGET_HOST=$(params.host)
      TARGET_HOST_USERNAME=$(params.username)
      TARGET_HOST_KEY_PATH=$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)/$(params.key)
      chmod 600 ${TARGET_HOST_KEY_PATH}
      TARGET_FOLDER=pd-e2e
      TARGET_RESULTS=$(params.results-folder)
      TARGET_CLEANUP=$(params.target-cleanup)
      OUTPUT_FOLDER=$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)/$(params.workspace-qe-subpath)
      mkdir -p "${OUTPUT_FOLDER}"
      
      # Create command - command to sbustitue from GHA workflow using images
      if [[ $(params.os) == "windows" ]]; then
        cmd="${TARGET_FOLDER}/builder.ps1 "
        cmd="$cmd -targetFolder ${TARGET_FOLDER} "
        cmd="$cmd -resultsFolder ${TARGET_RESULTS} "
        cmd="$cmd -fork $(params.fork) "
        cmd="$cmd -branch $(params.branch)"
      fi
      if [[ $(params.os) == "darwin" ]]; then
        cmd="${TARGET_FOLDER}/builder.sh "
        cmd="$cmd --targetFolder ${TARGET_FOLDER} "
        cmd="$cmd --resultsFolder ${TARGET_RESULTS} "
        cmd="$cmd --fork $(params.fork) "
        cmd="$cmd --branch $(params.branch)" 
      fi
      
      # Exec
      . entrypoint.sh "${cmd}"

      # Results
      echo -n "${SECONDS}" | tee $(results.duration.path)
      # use this example to fill the value of the pd-path into results
      ls -R ${OUTPUT_FOLDER}
      echo -n "$(cat ${OUTPUT_FOLDER}/${TARGET_RESULTS}/pde2e-binary-path.log)" | tee $(results.pd-path.path)
      
    resources:      
      requests:
        memory: "50Mi"
        cpu: "5m"
      limits:
        memory: "70Mi"
        cpu: "10m"

  sidecars:
  - name: fake-rdp
    image: quay.io/rhqp/frdp:v0.0.1
    imagePullPolicy: Always
    env:
    - name: RDP_HOST
      value: $(params.host)
    - name: RDP_USER
      value: $(params.username)
    - name: RDP_PASSWORD
      value: $(params.userpassword)
    script: |
      #!/bin/sh
      
      # Sidecar is used to create a fake RDP connection, this is only required for windows
      if [[ $(params.os) == "windows" ]]; then
        . entrypoint.sh
      fi
      
    resources:      
      requests:
        memory: "30Mi"
        cpu: "5m"
      limits:
        memory: "70Mi"
        cpu: "10m"